name: Close stale issues

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been inactive for 14 days and will be automatically closed if there is no further activity."
          close-issue-message: "This issue was automatically closed due to inactivity."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
